<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href='/css/style.css' rel='stylesheet' type='text/css'>

    </head>
    <body>

        <section id="news">
            <h1 class="Title">News</h1>
            <div class="items">
            <?php foreach ($news as $item) { ?>
                <div class="item">
                    <div class="item-image">
                        <a href="/<?php echo $item['slug']; ?>">
                            <img src="<?php echo $item['image']; ?>">
                        </a>
                    </div>
                    <div class="item-title">
                        <a href="/<?php echo $item['slug']; ?>">
                            <?php echo $item['title']; ?>
                        </a>
                    </div>
                </div>
            <?php } ?>
            </div>
        </section>

    </body>
</html>
